language: node_js
branches:
  only:
  - master
notifications:
  email: true
cache:
  directories:
    - node_modules
node_js:
- '6'
before_script:
    - npm install -g firebase-tools
script:
- npm run build
after_success:
  - firebase deploy --token="${FIREBASE_TOKEN}" --message="${TRAVIS_COMMIT}"